CREATE DATABASE SVLT20232108
USE SVLT20232108
CREATE TABLE [Books]
(
    Id INT IDENTITY PRIMARY KEY,
    Titulo VARCHAR(50) NOT NULL,
    Autor VARCHAR(50) NOT NULL,
    Año CHAR(4) NOT NULL
)

INSERT INTO [Books] (Titulo,Autor,Año) 
VALUES('La Divina Comedia','Dante',1472);